"""
Stock Analysis & Portfolio Risk Dashboard
------------------------------------------
Fetches data from Yahoo Finance (yfinance) and provides:
  1. Price charts across all available timeframes
  2. Pivot-point support & resistance levels
  3. RSI & MACD indicators
  4. Overbought / oversold detection via mean-reversion (z-score + Bollinger Bands)
  5. Fundamental analysis snapshot
  6. A rule-based "AI" Buy / Sell / Hold recommendation engine (NO external API / API key used)
  7. A Portfolio tab: upload holdings, get live valuation, historical & stressed VaR
     (99th percentile, both downside and upside), and rule-based rebalancing suggestions

DISCLAIMER: This tool is for educational purposes only. It is NOT financial advice.
All recommendations are generated by simple, transparent, rule-based heuristics
computed locally -- there is no external AI/LLM API involved. Always do your own
research or consult a licensed financial advisor before making investment decisions.
"""

import warnings
from datetime import datetime

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st
import yfinance as yf
from scipy.stats import norm

warnings.filterwarnings("ignore")

st.set_page_config(page_title="Stock & Portfolio Analyzer", layout="wide")

# =============================================================================
# CONSTANTS
# =============================================================================

PERIOD_OPTIONS = {
    "1 Day": "1d",
    "5 Days": "5d",
    "1 Month": "1mo",
    "3 Months": "3mo",
    "6 Months": "6mo",
    "YTD": "ytd",
    "1 Year": "1y",
    "2 Years": "2y",
    "5 Years": "5y",
    "10 Years": "10y",
    "Max": "max",
}

INTERVAL_MAP = {
    "1d": "5m", "5d": "15m", "1mo": "1d", "3mo": "1d", "6mo": "1d",
    "ytd": "1d", "1y": "1d", "2y": "1wk", "5y": "1wk", "10y": "1mo", "max": "1mo",
}

Z_99 = norm.ppf(0.99)  # ~2.326


# =============================================================================
# DATA FETCH HELPERS (cached)
# =============================================================================

@st.cache_data(ttl=300, show_spinner=False)
def fetch_history(ticker: str, period: str, interval: str) -> pd.DataFrame:
    df = yf.Ticker(ticker).history(period=period, interval=interval, auto_adjust=False)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    return df


@st.cache_data(ttl=900, show_spinner=False)
def fetch_info(ticker: str) -> dict:
    try:
        info = yf.Ticker(ticker).get_info()
    except Exception:
        info = {}
    return info or {}


@st.cache_data(ttl=300, show_spinner=False)
def fetch_close_series(ticker: str, period: str) -> pd.Series:
    df = yf.Ticker(ticker).history(period=period, interval="1d", auto_adjust=True)
    if df.empty:
        return pd.Series(dtype=float)
    return df["Close"].rename(ticker)


@st.cache_data(ttl=300, show_spinner=False)
def fetch_last_price(ticker: str) -> float:
    try:
        fi = yf.Ticker(ticker).fast_info
        price = fi.get("lastPrice") or fi.get("last_price")
        if price:
            return float(price)
    except Exception:
        pass
    try:
        df = yf.Ticker(ticker).history(period="5d", interval="1d")
        if not df.empty:
            return float(df["Close"].iloc[-1])
    except Exception:
        pass
    return np.nan


# =============================================================================
# TECHNICAL INDICATORS
# =============================================================================

def compute_rsi(close: pd.Series, period: int = 14) -> pd.Series:
    delta = close.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.ewm(alpha=1 / period, min_periods=period, adjust=False).mean()
    avg_loss = loss.ewm(alpha=1 / period, min_periods=period, adjust=False).mean()
    rs = avg_gain / avg_loss.replace(0, np.nan)
    rsi = 100 - (100 / (1 + rs))
    return rsi.fillna(50)


def compute_macd(close: pd.Series, fast: int = 12, slow: int = 26, signal: int = 9):
    ema_fast = close.ewm(span=fast, adjust=False).mean()
    ema_slow = close.ewm(span=slow, adjust=False).mean()
    macd_line = ema_fast - ema_slow
    signal_line = macd_line.ewm(span=signal, adjust=False).mean()
    hist = macd_line - signal_line
    return macd_line, signal_line, hist


def compute_mean_reversion(close: pd.Series, window: int = 20):
    sma = close.rolling(window).mean()
    std = close.rolling(window).std()
    z = (close - sma) / std.replace(0, np.nan)
    upper_band = sma + 2 * std
    lower_band = sma - 2 * std
    return sma, std, z, upper_band, lower_band


def compute_pivot_points(df: pd.DataFrame, method: str = "Daily") -> dict:
    """Classic pivot points using the last COMPLETED period's H/L/C."""
    if method == "Weekly":
        agg = df.resample("W").agg({"High": "max", "Low": "min", "Close": "last"}).dropna()
    elif method == "Monthly":
        agg = df.resample("ME").agg({"High": "max", "Low": "min", "Close": "last"}).dropna()
    else:
        agg = df[["High", "Low", "Close"]].dropna()

    if len(agg) < 2:
        row = agg.iloc[-1]
    else:
        row = agg.iloc[-2]  # last completed period

    H, L, C = row["High"], row["Low"], row["Close"]
    P = (H + L + C) / 3
    R1 = 2 * P - L
    S1 = 2 * P - H
    R2 = P + (H - L)
    S2 = P - (H - L)
    R3 = H + 2 * (P - L)
    S3 = L - 2 * (H - P)
    return {"R3": R3, "R2": R2, "R1": R1, "Pivot": P, "S1": S1, "S2": S2, "S3": S3,
            "Ref High": H, "Ref Low": L, "Ref Close": C}


# =============================================================================
# RULE-BASED "AI" SCORING ENGINE (no external API / API key)
# =============================================================================

def score_technical(close: pd.Series) -> dict:
    rsi = compute_rsi(close)
    macd_line, signal_line, hist = compute_macd(close)
    sma, std, z, upper, lower = compute_mean_reversion(close)
    sma50 = close.rolling(50).mean()
    sma200 = close.rolling(200).mean()

    last_rsi = rsi.iloc[-1]
    last_macd, last_signal = macd_line.iloc[-1], signal_line.iloc[-1]
    last_z = z.iloc[-1] if not np.isnan(z.iloc[-1]) else 0
    last_price = close.iloc[-1]
    last_sma50 = sma50.iloc[-1] if not np.isnan(sma50.iloc[-1]) else last_price
    last_sma200 = sma200.iloc[-1] if len(sma200.dropna()) > 0 else last_price

    score = 0
    reasons = []

    if last_rsi < 30:
        score += 1; reasons.append(f"RSI is {last_rsi:.1f} (oversold, bullish)")
    elif last_rsi > 70:
        score -= 1; reasons.append(f"RSI is {last_rsi:.1f} (overbought, bearish)")
    else:
        reasons.append(f"RSI is {last_rsi:.1f} (neutral)")

    if last_macd > last_signal:
        score += 1; reasons.append("MACD line above signal line (bullish momentum)")
    else:
        score -= 1; reasons.append("MACD line below signal line (bearish momentum)")

    if last_z <= -2:
        score += 1; reasons.append(f"Price is {last_z:.2f} std below its 20-day mean (oversold, reversion-up expected)")
    elif last_z >= 2:
        score -= 1; reasons.append(f"Price is {last_z:.2f} std above its 20-day mean (overbought, reversion-down expected)")
    else:
        reasons.append(f"Price is within normal range of 20-day mean (z={last_z:.2f})")

    if last_price > last_sma50 > last_sma200:
        score += 1; reasons.append("Price above 50 & 200-day MA (uptrend)")
    elif last_price < last_sma50 < last_sma200:
        score -= 1; reasons.append("Price below 50 & 200-day MA (downtrend)")
    else:
        reasons.append("Mixed trend signal from moving averages")

    return {
        "rsi": last_rsi, "macd": last_macd, "signal": last_signal, "hist": hist.iloc[-1],
        "z_score": last_z, "upper_band": upper.iloc[-1], "lower_band": lower.iloc[-1],
        "score": score, "reasons": reasons,
        "overbought_oversold": (
            "Overbought" if (last_rsi > 70 or last_z >= 2) else
            "Oversold" if (last_rsi < 30 or last_z <= -2) else "Neutral"
        ),
    }


def score_fundamental(info: dict) -> dict:
    score = 0
    reasons = []

    pe = info.get("trailingPE")
    roe = info.get("returnOnEquity")
    margins = info.get("profitMargins")
    rev_growth = info.get("revenueGrowth")
    earn_growth = info.get("earningsGrowth")
    de = info.get("debtToEquity")

    if pe is not None:
        if 0 < pe < 25:
            score += 1; reasons.append(f"Trailing P/E of {pe:.1f} is reasonable")
        elif pe >= 40:
            score -= 1; reasons.append(f"Trailing P/E of {pe:.1f} looks expensive")

    if roe is not None:
        if roe > 0.15:
            score += 1; reasons.append(f"Strong ROE of {roe*100:.1f}%")
        elif roe < 0:
            score -= 1; reasons.append("Negative ROE")

    if margins is not None:
        if margins > 0.10:
            score += 1; reasons.append(f"Healthy profit margin of {margins*100:.1f}%")
        elif margins < 0:
            score -= 1; reasons.append("Negative profit margin")

    if rev_growth is not None:
        if rev_growth > 0.05:
            score += 1; reasons.append(f"Revenue growing at {rev_growth*100:.1f}%")
        elif rev_growth < 0:
            score -= 1; reasons.append("Revenue is declining")

    if earn_growth is not None and earn_growth < -0.10:
        score -= 1; reasons.append("Earnings declining sharply")

    if de is not None and de > 200:
        score -= 1; reasons.append(f"High debt-to-equity of {de:.0f}%")

    if not reasons:
        reasons.append("Insufficient fundamental data available from Yahoo Finance")

    return {"score": score, "reasons": reasons}


def final_recommendation(tech_score: int, fund_score: int):
    total = tech_score + fund_score
    if total >= 3:
        return "STRONG BUY", total
    elif total >= 1:
        return "BUY", total
    elif total <= -3:
        return "STRONG SELL", total
    elif total <= -1:
        return "SELL", total
    else:
        return "HOLD", total


# =============================================================================
# PORTFOLIO / VaR HELPERS
# =============================================================================

def build_portfolio_returns(tickers: list, period: str = "2y") -> pd.DataFrame:
    series_list = []
    for t in tickers:
        s = fetch_close_series(t, period)
        if not s.empty:
            series_list.append(s)
    if not series_list:
        return pd.DataFrame()
    prices = pd.concat(series_list, axis=1, join="inner")
    returns = prices.pct_change().dropna()
    return returns


def historical_var(port_returns: pd.Series, portfolio_value: float, pct: float = 1):
    downside = -np.percentile(port_returns, pct) * portfolio_value
    upside = np.percentile(port_returns, 100 - pct) * portfolio_value
    return downside, upside


def parametric_var(port_returns: pd.Series, portfolio_value: float, z: float = Z_99):
    mu, sigma = port_returns.mean(), port_returns.std()
    downside = -(mu - z * sigma) * portfolio_value
    upside = (mu + z * sigma) * portfolio_value
    return downside, upside


def stressed_var(port_returns: pd.Series, portfolio_value: float, window: int = 60, pct: float = 1):
    if len(port_returns) < window + 5:
        window = max(10, len(port_returns) // 2)
    rolling_vol = port_returns.rolling(window).std()
    if rolling_vol.dropna().empty:
        return None
    stress_end = rolling_vol.idxmax()
    stress_window = port_returns.loc[:stress_end].tail(window)
    downside = -np.percentile(stress_window, pct) * portfolio_value
    upside = np.percentile(stress_window, 100 - pct) * portfolio_value
    start_date = stress_window.index.min()
    end_date = stress_window.index.max()
    return downside, upside, start_date, end_date


# =============================================================================
# SIDEBAR
# =============================================================================

st.sidebar.title("Settings")
page = st.sidebar.radio("Navigate", ["Stock Analysis", "Portfolio Analysis"])

# =============================================================================
# PAGE 1: STOCK ANALYSIS
# =============================================================================

if page == "Stock Analysis":
    st.title("Stock Analysis Dashboard")
    st.caption("Data source: Yahoo Finance (via yfinance). Educational use only — not financial advice.")

    tickers_input = st.sidebar.text_input(
        "Ticker(s) — comma separated", value="AAPL, MSFT, TCS.NS"
    )
    tickers = [t.strip().upper() for t in tickers_input.split(",") if t.strip()]

    if not tickers:
        st.info("Enter at least one ticker in the sidebar (e.g. AAPL, MSFT, TCS.NS, RELIANCE.NS).")
        st.stop()

    active_ticker = st.sidebar.selectbox("Ticker for detailed view", tickers, index=0)

    period_label = st.sidebar.selectbox("Chart timeframe", list(PERIOD_OPTIONS.keys()), index=8)
    period = PERIOD_OPTIONS[period_label]
    interval = INTERVAL_MAP[period]

    pivot_method = st.sidebar.selectbox("Pivot point basis", ["Daily", "Weekly", "Monthly"], index=0)

    with st.spinner(f"Fetching data for {active_ticker}..."):
        hist = fetch_history(active_ticker, period, interval)
        info = fetch_info(active_ticker)

    if hist.empty:
        st.error(f"No data returned for '{active_ticker}'. Check the symbol and try again.")
        st.stop()

    close = hist["Close"].dropna()

    tabs = st.tabs([
        "1 Price Chart", "2 Support & Resistance", "3 RSI & MACD",
        "4 Overbought / Oversold", "5 Fundamentals", "6 AI Recommendation",
        "Compare All Tickers",
    ])

    # ---- Tab 1: Price chart (all timeframes) ----
    with tabs[0]:
        st.subheader(f"{active_ticker} — Price Chart ({period_label})")
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=hist.index, y=hist["Close"], mode="lines", name="Close"))
        fig.update_layout(height=480, xaxis_title="Date", yaxis_title="Price", hovermode="x unified")
        st.plotly_chart(fig, use_container_width=True)

        c1, c2, c3 = st.columns(3)
        chg = close.iloc[-1] - close.iloc[0]
        pct = (chg / close.iloc[0]) * 100 if close.iloc[0] else 0
        c1.metric("Latest Close", f"{close.iloc[-1]:.2f}")
        c2.metric(f"Change ({period_label})", f"{chg:+.2f}", f"{pct:+.2f}%")
        c3.metric("Data Points", len(close))

        with st.expander("Show raw OHLCV data"):
            st.dataframe(hist.sort_index(ascending=False), use_container_width=True)

    # ---- Tab 2: Support & Resistance (Pivot Points) ----
    with tabs[1]:
        st.subheader(f"{active_ticker} — Pivot Points ({pivot_method})")
        daily_hist = fetch_history(active_ticker, "1y", "1d")
        if daily_hist.empty:
            st.warning("Not enough daily data to compute pivot points.")
        else:
            pivots = compute_pivot_points(daily_hist, pivot_method)
            pv_df = pd.DataFrame({
                "Level": ["R3", "R2", "R1", "Pivot", "S1", "S2", "S3"],
                "Price": [pivots["R3"], pivots["R2"], pivots["R1"], pivots["Pivot"],
                          pivots["S1"], pivots["S2"], pivots["S3"]],
            })
            st.dataframe(pv_df.style.format({"Price": "{:.2f}"}), use_container_width=True, hide_index=True)
            st.caption(
                f"Based on last completed {pivot_method.lower()} period — "
                f"High: {pivots['Ref High']:.2f}, Low: {pivots['Ref Low']:.2f}, Close: {pivots['Ref Close']:.2f}"
            )

            fig2 = go.Figure()
            recent = daily_hist["Close"].tail(120)
            fig2.add_trace(go.Scatter(x=recent.index, y=recent, name="Close", line=dict(color="white")))
            colors = {"R3": "red", "R2": "red", "R1": "red", "Pivot": "yellow", "S1": "green", "S2": "green", "S3": "green"}
            for lvl in ["R3", "R2", "R1", "Pivot", "S1", "S2", "S3"]:
                fig2.add_hline(y=pivots[lvl], line_dash="dot", line_color=colors[lvl],
                                annotation_text=lvl, annotation_position="right")
            fig2.update_layout(height=480, title="Price vs Pivot Levels (last 120 sessions)")
            st.plotly_chart(fig2, use_container_width=True)

    # ---- Tab 3: RSI & MACD ----
    with tabs[2]:
        st.subheader(f"{active_ticker} — RSI & MACD")
        rsi = compute_rsi(close)
        macd_line, signal_line, hist_bar = compute_macd(close)

        fig3 = go.Figure()
        fig3.add_trace(go.Scatter(x=rsi.index, y=rsi, name="RSI (14)", line=dict(color="cyan")))
        fig3.add_hline(y=70, line_dash="dash", line_color="red", annotation_text="Overbought (70)")
        fig3.add_hline(y=30, line_dash="dash", line_color="green", annotation_text="Oversold (30)")
        fig3.update_layout(height=320, yaxis_range=[0, 100], title="RSI (14-period)")
        st.plotly_chart(fig3, use_container_width=True)

        fig4 = go.Figure()
        fig4.add_trace(go.Scatter(x=macd_line.index, y=macd_line, name="MACD", line=dict(color="orange")))
        fig4.add_trace(go.Scatter(x=signal_line.index, y=signal_line, name="Signal", line=dict(color="blue")))
        fig4.add_trace(go.Bar(x=hist_bar.index, y=hist_bar, name="Histogram", marker_color="gray"))
        fig4.update_layout(height=380, title="MACD (12, 26, 9)")
        st.plotly_chart(fig4, use_container_width=True)

        c1, c2, c3 = st.columns(3)
        c1.metric("RSI", f"{rsi.iloc[-1]:.1f}")
        c2.metric("MACD", f"{macd_line.iloc[-1]:.3f}")
        c3.metric("Signal", f"{signal_line.iloc[-1]:.3f}")

    # ---- Tab 4: Overbought / Oversold (Mean Reversion) ----
    with tabs[3]:
        st.subheader(f"{active_ticker} — Mean Reversion (Overbought / Oversold)")
        sma, std, z, upper, lower = compute_mean_reversion(close)

        fig5 = go.Figure()
        fig5.add_trace(go.Scatter(x=close.index, y=close, name="Close", line=dict(color="white")))
        fig5.add_trace(go.Scatter(x=sma.index, y=sma, name="20-day SMA", line=dict(color="yellow")))
        fig5.add_trace(go.Scatter(x=upper.index, y=upper, name="Upper Band (+2σ)", line=dict(color="red", dash="dot")))
        fig5.add_trace(go.Scatter(x=lower.index, y=lower, name="Lower Band (-2σ)", line=dict(color="green", dash="dot")))
        fig5.update_layout(height=480, title="Bollinger-style Mean Reversion Bands")
        st.plotly_chart(fig5, use_container_width=True)

        last_z = z.iloc[-1]
        condition = "Overbought" if last_z >= 2 else "Oversold" if last_z <= -2 else "Neutral"
        c1, c2 = st.columns(2)
        c1.metric("Z-score vs 20-day mean", f"{last_z:.2f}")
        c2.metric("Mean-Reversion Signal", condition)
        st.caption(
            "Methodology: z-score = (Price − 20-day mean) / 20-day std-dev. "
            "|z| ≥ 2 is treated as a statistically significant deviation suggesting a reversion "
            "back toward the mean is more likely (not guaranteed)."
        )

    # ---- Tab 5: Fundamentals ----
    with tabs[4]:
        st.subheader(f"{active_ticker} — Fundamental Snapshot")
        if not info:
            st.warning("Fundamental data not available for this ticker.")
        else:
            def fmt(key, pct=False, default="N/A"):
                v = info.get(key)
                if v is None:
                    return default
                if pct:
                    return f"{v*100:.2f}%"
                return f"{v:,.2f}" if isinstance(v, (int, float)) else str(v)

            fcol1, fcol2, fcol3 = st.columns(3)
            fcol1.metric("Market Cap", fmt("marketCap"))
            fcol1.metric("Trailing P/E", fmt("trailingPE"))
            fcol1.metric("Forward P/E", fmt("forwardPE"))
            fcol2.metric("Price / Book", fmt("priceToBook"))
            fcol2.metric("ROE", fmt("returnOnEquity", pct=True))
            fcol2.metric("ROA", fmt("returnOnAssets", pct=True))
            fcol3.metric("Profit Margin", fmt("profitMargins", pct=True))
            fcol3.metric("Revenue Growth", fmt("revenueGrowth", pct=True))
            fcol3.metric("Debt/Equity", fmt("debtToEquity"))

            fcol4, fcol5, fcol6 = st.columns(3)
            fcol4.metric("Dividend Yield", fmt("dividendYield", pct=True))
            fcol5.metric("Beta", fmt("beta"))
            fcol6.metric("52-Week Range",
                         f"{info.get('fiftyTwoWeekLow', 'N/A')} - {info.get('fiftyTwoWeekHigh', 'N/A')}")

            with st.expander("Business Summary"):
                st.write(info.get("longBusinessSummary", "N/A"))

    # ---- Tab 6: AI Recommendation ----
    with tabs[5]:
        st.subheader(f"{active_ticker} — Rule-Based AI Signal")
        st.caption("Generated locally via a transparent weighted-scoring model — no external AI API is used.")

        tech = score_technical(close)
        fund = score_fundamental(info)
        rec, total_score = final_recommendation(tech["score"], fund["score"])

        color_map = {"STRONG BUY": "green", "BUY": "green", "HOLD": "orange", "SELL": "red", "STRONG SELL": "red"}
        st.markdown(f"### Recommendation: :{color_map[rec]}[{rec}]  (score: {total_score:+d})")

        c1, c2 = st.columns(2)
        with c1:
            st.markdown("**Technical factors**")
            for r in tech["reasons"]:
                st.write(f"- {r}")
        with c2:
            st.markdown("**Fundamental factors**")
            for r in fund["reasons"]:
                st.write(f"- {r}")

        st.info(
            "This is a simple rule-based heuristic for educational purposes, not investment advice. "
            "Markets can behave irrationally and no model guarantees future performance."
        )

    # ---- Tab 7: Compare all entered tickers ----
    with tabs[6]:
        st.subheader("Comparison — All Entered Tickers")
        rows = []
        with st.spinner("Scoring all tickers..."):
            for t in tickers:
                h = fetch_history(t, "1y", "1d")
                if h.empty:
                    continue
                c = h["Close"].dropna()
                i = fetch_info(t)
                tech_t = score_technical(c)
                fund_t = score_fundamental(i)
                rec_t, score_t = final_recommendation(tech_t["score"], fund_t["score"])
                rows.append({
                    "Ticker": t,
                    "Price": round(c.iloc[-1], 2),
                    "RSI": round(tech_t["rsi"], 1),
                    "Signal (RSI/MACD)": tech_t["overbought_oversold"],
                    "Tech Score": tech_t["score"],
                    "Fund Score": fund_t["score"],
                    "Recommendation": rec_t,
                })
        if rows:
            st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)
        else:
            st.warning("No valid data could be retrieved for the entered tickers.")

# =============================================================================
# PAGE 2: PORTFOLIO ANALYSIS
# =============================================================================

else:
    st.title("Portfolio Analysis & Risk Dashboard")
    st.caption("Upload your holdings for live valuation, VaR / Stressed VaR, and rule-based rebalancing hints.")

    st.markdown("**Expected file format** (CSV or Excel) with columns: `Ticker`, `Quantity`, and optionally `AvgBuyPrice`.")
    sample = pd.DataFrame({
        "Ticker": ["AAPL", "MSFT", "TCS.NS"],
        "Quantity": [10, 5, 20],
        "AvgBuyPrice": [180.0, 300.0, 3500.0],
    })
    st.download_button(
        "Download sample template",
        data=sample.to_csv(index=False).encode("utf-8"),
        file_name="portfolio_template.csv",
        mime="text/csv",
    )

    uploaded = st.file_uploader("Upload your portfolio", type=["csv", "xlsx"])

    lookback_label = st.selectbox("Historical lookback for risk calculations", list(PERIOD_OPTIONS.keys())[2:], index=6)
    lookback_period = PERIOD_OPTIONS[lookback_label]

    if uploaded is None:
        st.info("Upload a CSV/Excel file to begin (or download the template above to see the format).")
        st.stop()

    try:
        if uploaded.name.endswith(".csv"):
            port_df = pd.read_csv(uploaded)
        else:
            port_df = pd.read_excel(uploaded)
    except Exception as e:
        st.error(f"Could not read file: {e}")
        st.stop()

    port_df.columns = [c.strip() for c in port_df.columns]
    if "Ticker" not in port_df.columns or "Quantity" not in port_df.columns:
        st.error("File must contain at least 'Ticker' and 'Quantity' columns.")
        st.stop()

    port_df["Ticker"] = port_df["Ticker"].astype(str).str.strip().str.upper()
    port_df = port_df.dropna(subset=["Ticker", "Quantity"])

    with st.spinner("Fetching live prices..."):
        port_df["LivePrice"] = port_df["Ticker"].apply(fetch_last_price)

    port_df = port_df.dropna(subset=["LivePrice"])
    if port_df.empty:
        st.error("Could not fetch prices for any ticker in the uploaded file. Check the symbols.")
        st.stop()

    port_df["MarketValue"] = port_df["Quantity"] * port_df["LivePrice"]
    total_value = port_df["MarketValue"].sum()
    port_df["Weight %"] = 100 * port_df["MarketValue"] / total_value

    if "AvgBuyPrice" in port_df.columns:
        port_df["Invested"] = port_df["Quantity"] * port_df["AvgBuyPrice"]
        port_df["P&L"] = port_df["MarketValue"] - port_df["Invested"]
        port_df["P&L %"] = 100 * port_df["P&L"] / port_df["Invested"]

    st.subheader("Portfolio Snapshot")
    st.dataframe(port_df.round(2), use_container_width=True, hide_index=True)

    c1, c2, c3 = st.columns(3)
    c1.metric("Total Portfolio Value", f"{total_value:,.2f}")
    if "P&L" in port_df.columns:
        total_pl = port_df["P&L"].sum()
        total_invested = port_df["Invested"].sum()
        c2.metric("Total P&L", f"{total_pl:,.2f}", f"{100*total_pl/total_invested:+.2f}%")
    c3.metric("Number of Holdings", len(port_df))

    fig_pie = go.Figure(data=[go.Pie(labels=port_df["Ticker"], values=port_df["MarketValue"], hole=0.4)])
    fig_pie.update_layout(height=420, title="Portfolio Allocation")
    st.plotly_chart(fig_pie, use_container_width=True)

    # ---- Historical returns for VaR ----
    st.subheader("Value at Risk (VaR) & Stressed VaR — 99th Percentile")
    tickers_list = port_df["Ticker"].tolist()

    with st.spinner("Downloading historical prices for risk calculations..."):
        returns = build_portfolio_returns(tickers_list, lookback_period)

    if returns.empty or returns.shape[1] < 1:
        st.warning("Not enough historical data to compute portfolio risk metrics.")
    else:
        # Align weights to whichever tickers actually returned data
        valid_tickers = list(returns.columns)
        valid_weights = port_df.set_index("Ticker").loc[valid_tickers, "MarketValue"].values
        valid_weights = valid_weights / valid_weights.sum()

        port_returns = (returns[valid_tickers] * valid_weights).sum(axis=1)

        h_down, h_up = historical_var(port_returns, total_value, pct=1)
        p_down, p_up = parametric_var(port_returns, total_value, z=Z_99)
        s_result = stressed_var(port_returns, total_value, window=60, pct=1)

        st.markdown("**Historical Simulation VaR (99th percentile, 1-day horizon)**")
        c1, c2 = st.columns(2)
        c1.metric("Downside VaR (99%)", f"{h_down:,.2f}", help="Estimated max 1-day loss not expected to be exceeded 99% of the time.")
        c2.metric("Upside VaR (99%)", f"{h_up:,.2f}", help="Estimated max 1-day gain not expected to be exceeded 99% of the time.")

        st.markdown("**Parametric (Variance-Covariance) VaR (99th percentile, 1-day horizon)**")
        c3, c4 = st.columns(2)
        c3.metric("Downside VaR (99%)", f"{p_down:,.2f}")
        c4.metric("Upside VaR (99%)", f"{p_up:,.2f}")

        if s_result:
            s_down, s_up, s_start, s_end = s_result
            st.markdown(
                f"**Stressed VaR (SVaR, 99th percentile)** — based on the highest-volatility "
                f"60-day window observed: {s_start.date()} to {s_end.date()}"
            )
            c5, c6 = st.columns(2)
            c5.metric("Stressed Downside VaR (99%)", f"{s_down:,.2f}")
            c6.metric("Stressed Upside VaR (99%)", f"{s_up:,.2f}")

        with st.expander("Methodology"):
            st.markdown(
                "- **Historical VaR**: 1st / 99th percentile of actual historical daily portfolio returns, "
                "scaled by current portfolio value.\n"
                "- **Parametric VaR**: assumes normally distributed returns; "
                "VaR = (μ ± z·σ) × portfolio value, z(99%) ≈ 2.326.\n"
                "- **Stressed VaR**: identifies the historical 60-day window with the highest realized "
                "volatility (e.g. a past market stress period) and applies historical simulation VaR "
                "within that window — a proxy for how the current portfolio might behave under stress.\n"
                "- All figures are **1-day** estimates in portfolio currency terms and are backward-looking; "
                "they are not a guarantee of future losses/gains."
            )

        fig_ret = go.Figure()
        fig_ret.add_trace(go.Histogram(x=port_returns * 100, nbinsx=50, name="Daily Returns %"))
        fig_ret.update_layout(height=380, title="Distribution of Historical Portfolio Daily Returns (%)",
                               xaxis_title="Daily Return (%)")
        st.plotly_chart(fig_ret, use_container_width=True)

        # ---- AI-style rebalancing suggestions (rule-based, no API) ----
        st.subheader("AI Portfolio Suggestions (Rule-Based, No External API)")
        suggestions = []

        # Concentration risk
        for _, row in port_df.iterrows():
            if row["Weight %"] > 25:
                suggestions.append(
                    f"**{row['Ticker']}** makes up {row['Weight %']:.1f}% of the portfolio — "
                    "consider trimming to reduce concentration risk."
                )

        # Per-holding technical/fundamental score
        for t in valid_tickers:
            h = fetch_history(t, "1y", "1d")
            if h.empty:
                continue
            c = h["Close"].dropna()
            i = fetch_info(t)
            tech_t = score_technical(c)
            fund_t = score_fundamental(i)
            rec_t, score_t = final_recommendation(tech_t["score"], fund_t["score"])
            weight_row = port_df.loc[port_df["Ticker"] == t, "Weight %"]
            w = weight_row.values[0] if not weight_row.empty else 0
            if rec_t in ("SELL", "STRONG SELL") and w > 10:
                suggestions.append(
                    f"**{t}** shows a {rec_t} signal (score {score_t:+d}) and is {w:.1f}% of the portfolio — "
                    "consider reducing exposure."
                )
            elif rec_t in ("BUY", "STRONG BUY") and w < 5:
                suggestions.append(
                    f"**{t}** shows a {rec_t} signal (score {score_t:+d}) but is only {w:.1f}% of the portfolio — "
                    "could be a candidate to add to on strength."
                )

        # Volatility / risk concentration
        ann_vol = port_returns.std() * np.sqrt(252) * 100
        if ann_vol > 35:
            suggestions.append(
                f"Annualized portfolio volatility is high (~{ann_vol:.1f}%) — "
                "consider adding lower-volatility / defensive names to diversify risk."
            )

        if not suggestions:
            suggestions.append("No major red flags detected — portfolio looks reasonably balanced based on current rules.")

        for s in suggestions:
            st.markdown(f"- {s}")

        st.info(
            "These suggestions come from simple, transparent rules (concentration limits, technical/"
            "fundamental scores, volatility thresholds) computed locally — no external AI/LLM API is used. "
            "This is not financial advice."
        )

st.sidebar.markdown("---")
st.sidebar.caption(f"Last refreshed: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
st.sidebar.caption("Educational tool only — not financial advice.")
